os: linux
dist: bionic
language: rust

services:
  - docker

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
      before_install: sudo apt-get install -y build-essential clang libdbus-1-dev libssl-dev libsystemd-dev libudev-dev unzip
      script: (cd linux && cargo build --verbose --all && cargo test --verbose --all)
    - rust: beta
      before_install: sudo apt-get install -y build-essential clang libdbus-1-dev libssl-dev libsystemd-dev libudev-dev unzip
      script: (cd linux && cargo build --verbose --all && cargo test --verbose --all)
    - rust: nightly
      before_install: sudo apt-get install -y build-essential clang libdbus-1-dev libssl-dev libsystemd-dev libudev-dev unzip
      script: (cd linux && cargo build --verbose --all && cargo test --verbose --all)
    - env:
        - base=fedora
        - image=fedora
        - tag=30
      deploy:
        provider: packagecloud
        skip_cleanup: true
        dist: fedora/30
        local_dir: dist/fedora/30/
        repository: softu2f
        username: danstiner
        token:
          secure: 0biLRJWDCLduK5qWfI5I1SwapD8HGaAQncsJf4lKyAwzZOLLjQAs7cIoIbcOEBXXUeqG4+3/+/eUWrjCYzMJJ0nh6ciiDFVkiibLzIQ3w25l2i9slCBW3hHDxtN18JDlI0lm19YhMU4pM3jc2Ulkmq0Ek/9625ob2MDl8apt2vUYyusWuoLck4A0iyyL7rgng510tNT3S+YzU05FwJ7cwtoqst1PIB6mhYfGsVytBx7HU2hSueZkMyR975sD4ZgSP/57yxuaSe5sASYd+xBR+w6I3zcBr2FObB2EbyE8r1aDCR25gpUMwrmnfBpw7grcn/UFKB7a+d5iB5qtY8YjJ25sWqriut20qZWilEK5OLh3vLg/H0vIkUU8+XBZC/0DC2zxITpSrTH7rhWOYkfD1o9dl3B3JmTtM4V4ah8H7t0dnLvMZQzfu6voUfkQVb9cVSDLaiu9BQqHER/7ngAC0treiPrH6gpcOVeUxkNknJqummxA5avcwqwvvvY6PXDWzoI+43Llk27fyM/o75yCUL6DuBjKhKBnIZv8XIEnov4hNFFwaKKNC6J3cvlh+I6SMCtxftUAgACDSgw1ZZAD0u9K9OMNMt+QvSpH2rN+QByCgO1oF8/lCP1mg/9ZWFnS6C+YfZPLlwsTUuYJxwur3eG4tYabmzFRMeD9DQ/3FO4=
    - if: tag IS present
      env:
        - base=fedora
        - image=fedora
        - tag=29
      deploy:
        provider: packagecloud
        skip_cleanup: true
        dist: fedora/29
        local_dir: dist/fedora/29/
        repository: softu2f
        username: danstiner
        token:
          secure: 0biLRJWDCLduK5qWfI5I1SwapD8HGaAQncsJf4lKyAwzZOLLjQAs7cIoIbcOEBXXUeqG4+3/+/eUWrjCYzMJJ0nh6ciiDFVkiibLzIQ3w25l2i9slCBW3hHDxtN18JDlI0lm19YhMU4pM3jc2Ulkmq0Ek/9625ob2MDl8apt2vUYyusWuoLck4A0iyyL7rgng510tNT3S+YzU05FwJ7cwtoqst1PIB6mhYfGsVytBx7HU2hSueZkMyR975sD4ZgSP/57yxuaSe5sASYd+xBR+w6I3zcBr2FObB2EbyE8r1aDCR25gpUMwrmnfBpw7grcn/UFKB7a+d5iB5qtY8YjJ25sWqriut20qZWilEK5OLh3vLg/H0vIkUU8+XBZC/0DC2zxITpSrTH7rhWOYkfD1o9dl3B3JmTtM4V4ah8H7t0dnLvMZQzfu6voUfkQVb9cVSDLaiu9BQqHER/7ngAC0treiPrH6gpcOVeUxkNknJqummxA5avcwqwvvvY6PXDWzoI+43Llk27fyM/o75yCUL6DuBjKhKBnIZv8XIEnov4hNFFwaKKNC6J3cvlh+I6SMCtxftUAgACDSgw1ZZAD0u9K9OMNMt+QvSpH2rN+QByCgO1oF8/lCP1mg/9ZWFnS6C+YfZPLlwsTUuYJxwur3eG4tYabmzFRMeD9DQ/3FO4=
    - if: tag IS present
      env:
        - base=fedora
        - image=fedora
        - tag=28
      deploy:
        provider: packagecloud
        skip_cleanup: true
        dist: fedora/28
        local_dir: dist/fedora/28/
        repository: softu2f
        username: danstiner
        token:
          secure: 0biLRJWDCLduK5qWfI5I1SwapD8HGaAQncsJf4lKyAwzZOLLjQAs7cIoIbcOEBXXUeqG4+3/+/eUWrjCYzMJJ0nh6ciiDFVkiibLzIQ3w25l2i9slCBW3hHDxtN18JDlI0lm19YhMU4pM3jc2Ulkmq0Ek/9625ob2MDl8apt2vUYyusWuoLck4A0iyyL7rgng510tNT3S+YzU05FwJ7cwtoqst1PIB6mhYfGsVytBx7HU2hSueZkMyR975sD4ZgSP/57yxuaSe5sASYd+xBR+w6I3zcBr2FObB2EbyE8r1aDCR25gpUMwrmnfBpw7grcn/UFKB7a+d5iB5qtY8YjJ25sWqriut20qZWilEK5OLh3vLg/H0vIkUU8+XBZC/0DC2zxITpSrTH7rhWOYkfD1o9dl3B3JmTtM4V4ah8H7t0dnLvMZQzfu6voUfkQVb9cVSDLaiu9BQqHER/7ngAC0treiPrH6gpcOVeUxkNknJqummxA5avcwqwvvvY6PXDWzoI+43Llk27fyM/o75yCUL6DuBjKhKBnIZv8XIEnov4hNFFwaKKNC6J3cvlh+I6SMCtxftUAgACDSgw1ZZAD0u9K9OMNMt+QvSpH2rN+QByCgO1oF8/lCP1mg/9ZWFnS6C+YfZPLlwsTUuYJxwur3eG4tYabmzFRMeD9DQ/3FO4=
    - if: tag IS present
      env:
        - base=debian
        - image=debian
        - tag=bullseye
      deploy:
        provider: packagecloud
        skip_cleanup: true
        dist: debian/bullseye
        local_dir: dist/debian/bullseye/
        repository: softu2f
        username: danstiner
        token:
          secure: 0biLRJWDCLduK5qWfI5I1SwapD8HGaAQncsJf4lKyAwzZOLLjQAs7cIoIbcOEBXXUeqG4+3/+/eUWrjCYzMJJ0nh6ciiDFVkiibLzIQ3w25l2i9slCBW3hHDxtN18JDlI0lm19YhMU4pM3jc2Ulkmq0Ek/9625ob2MDl8apt2vUYyusWuoLck4A0iyyL7rgng510tNT3S+YzU05FwJ7cwtoqst1PIB6mhYfGsVytBx7HU2hSueZkMyR975sD4ZgSP/57yxuaSe5sASYd+xBR+w6I3zcBr2FObB2EbyE8r1aDCR25gpUMwrmnfBpw7grcn/UFKB7a+d5iB5qtY8YjJ25sWqriut20qZWilEK5OLh3vLg/H0vIkUU8+XBZC/0DC2zxITpSrTH7rhWOYkfD1o9dl3B3JmTtM4V4ah8H7t0dnLvMZQzfu6voUfkQVb9cVSDLaiu9BQqHER/7ngAC0treiPrH6gpcOVeUxkNknJqummxA5avcwqwvvvY6PXDWzoI+43Llk27fyM/o75yCUL6DuBjKhKBnIZv8XIEnov4hNFFwaKKNC6J3cvlh+I6SMCtxftUAgACDSgw1ZZAD0u9K9OMNMt+QvSpH2rN+QByCgO1oF8/lCP1mg/9ZWFnS6C+YfZPLlwsTUuYJxwur3eG4tYabmzFRMeD9DQ/3FO4=
    - if: tag IS present
      env:
        - base=debian
        - image=debian
        - tag=buster
      deploy:
        provider: packagecloud
        skip_cleanup: true
        dist: debian/buster
        local_dir: dist/debian/buster/
        repository: softu2f
        username: danstiner
        token:
          secure: 0biLRJWDCLduK5qWfI5I1SwapD8HGaAQncsJf4lKyAwzZOLLjQAs7cIoIbcOEBXXUeqG4+3/+/eUWrjCYzMJJ0nh6ciiDFVkiibLzIQ3w25l2i9slCBW3hHDxtN18JDlI0lm19YhMU4pM3jc2Ulkmq0Ek/9625ob2MDl8apt2vUYyusWuoLck4A0iyyL7rgng510tNT3S+YzU05FwJ7cwtoqst1PIB6mhYfGsVytBx7HU2hSueZkMyR975sD4ZgSP/57yxuaSe5sASYd+xBR+w6I3zcBr2FObB2EbyE8r1aDCR25gpUMwrmnfBpw7grcn/UFKB7a+d5iB5qtY8YjJ25sWqriut20qZWilEK5OLh3vLg/H0vIkUU8+XBZC/0DC2zxITpSrTH7rhWOYkfD1o9dl3B3JmTtM4V4ah8H7t0dnLvMZQzfu6voUfkQVb9cVSDLaiu9BQqHER/7ngAC0treiPrH6gpcOVeUxkNknJqummxA5avcwqwvvvY6PXDWzoI+43Llk27fyM/o75yCUL6DuBjKhKBnIZv8XIEnov4hNFFwaKKNC6J3cvlh+I6SMCtxftUAgACDSgw1ZZAD0u9K9OMNMt+QvSpH2rN+QByCgO1oF8/lCP1mg/9ZWFnS6C+YfZPLlwsTUuYJxwur3eG4tYabmzFRMeD9DQ/3FO4=
    - if: tag IS present
      env:
        - base=debian
        - image=debian
        - tag=stretch
      deploy:
        provider: packagecloud
        skip_cleanup: true
        dist: debian/stretch
        local_dir: dist/debian/stretch/
        repository: softu2f
        username: danstiner
        token:
          secure: 0biLRJWDCLduK5qWfI5I1SwapD8HGaAQncsJf4lKyAwzZOLLjQAs7cIoIbcOEBXXUeqG4+3/+/eUWrjCYzMJJ0nh6ciiDFVkiibLzIQ3w25l2i9slCBW3hHDxtN18JDlI0lm19YhMU4pM3jc2Ulkmq0Ek/9625ob2MDl8apt2vUYyusWuoLck4A0iyyL7rgng510tNT3S+YzU05FwJ7cwtoqst1PIB6mhYfGsVytBx7HU2hSueZkMyR975sD4ZgSP/57yxuaSe5sASYd+xBR+w6I3zcBr2FObB2EbyE8r1aDCR25gpUMwrmnfBpw7grcn/UFKB7a+d5iB5qtY8YjJ25sWqriut20qZWilEK5OLh3vLg/H0vIkUU8+XBZC/0DC2zxITpSrTH7rhWOYkfD1o9dl3B3JmTtM4V4ah8H7t0dnLvMZQzfu6voUfkQVb9cVSDLaiu9BQqHER/7ngAC0treiPrH6gpcOVeUxkNknJqummxA5avcwqwvvvY6PXDWzoI+43Llk27fyM/o75yCUL6DuBjKhKBnIZv8XIEnov4hNFFwaKKNC6J3cvlh+I6SMCtxftUAgACDSgw1ZZAD0u9K9OMNMt+QvSpH2rN+QByCgO1oF8/lCP1mg/9ZWFnS6C+YfZPLlwsTUuYJxwur3eG4tYabmzFRMeD9DQ/3FO4=
    - env:
        - base=debian
        - image=ubuntu
        - tag=eoan
      deploy:
        provider: packagecloud
        skip_cleanup: true
        dist: ubuntu/eoan
        local_dir: dist/ubuntu/eoan/
        repository: softu2f
        username: danstiner
        token:
          secure: 0biLRJWDCLduK5qWfI5I1SwapD8HGaAQncsJf4lKyAwzZOLLjQAs7cIoIbcOEBXXUeqG4+3/+/eUWrjCYzMJJ0nh6ciiDFVkiibLzIQ3w25l2i9slCBW3hHDxtN18JDlI0lm19YhMU4pM3jc2Ulkmq0Ek/9625ob2MDl8apt2vUYyusWuoLck4A0iyyL7rgng510tNT3S+YzU05FwJ7cwtoqst1PIB6mhYfGsVytBx7HU2hSueZkMyR975sD4ZgSP/57yxuaSe5sASYd+xBR+w6I3zcBr2FObB2EbyE8r1aDCR25gpUMwrmnfBpw7grcn/UFKB7a+d5iB5qtY8YjJ25sWqriut20qZWilEK5OLh3vLg/H0vIkUU8+XBZC/0DC2zxITpSrTH7rhWOYkfD1o9dl3B3JmTtM4V4ah8H7t0dnLvMZQzfu6voUfkQVb9cVSDLaiu9BQqHER/7ngAC0treiPrH6gpcOVeUxkNknJqummxA5avcwqwvvvY6PXDWzoI+43Llk27fyM/o75yCUL6DuBjKhKBnIZv8XIEnov4hNFFwaKKNC6J3cvlh+I6SMCtxftUAgACDSgw1ZZAD0u9K9OMNMt+QvSpH2rN+QByCgO1oF8/lCP1mg/9ZWFnS6C+YfZPLlwsTUuYJxwur3eG4tYabmzFRMeD9DQ/3FO4=
    - if: tag IS present
      env:
        - base=debian
        - image=ubuntu
        - tag=disco
      deploy:
        provider: packagecloud
        skip_cleanup: true
        dist: ubuntu/disco
        local_dir: dist/ubuntu/disco/
        repository: softu2f
        username: danstiner
        token:
          secure: 0biLRJWDCLduK5qWfI5I1SwapD8HGaAQncsJf4lKyAwzZOLLjQAs7cIoIbcOEBXXUeqG4+3/+/eUWrjCYzMJJ0nh6ciiDFVkiibLzIQ3w25l2i9slCBW3hHDxtN18JDlI0lm19YhMU4pM3jc2Ulkmq0Ek/9625ob2MDl8apt2vUYyusWuoLck4A0iyyL7rgng510tNT3S+YzU05FwJ7cwtoqst1PIB6mhYfGsVytBx7HU2hSueZkMyR975sD4ZgSP/57yxuaSe5sASYd+xBR+w6I3zcBr2FObB2EbyE8r1aDCR25gpUMwrmnfBpw7grcn/UFKB7a+d5iB5qtY8YjJ25sWqriut20qZWilEK5OLh3vLg/H0vIkUU8+XBZC/0DC2zxITpSrTH7rhWOYkfD1o9dl3B3JmTtM4V4ah8H7t0dnLvMZQzfu6voUfkQVb9cVSDLaiu9BQqHER/7ngAC0treiPrH6gpcOVeUxkNknJqummxA5avcwqwvvvY6PXDWzoI+43Llk27fyM/o75yCUL6DuBjKhKBnIZv8XIEnov4hNFFwaKKNC6J3cvlh+I6SMCtxftUAgACDSgw1ZZAD0u9K9OMNMt+QvSpH2rN+QByCgO1oF8/lCP1mg/9ZWFnS6C+YfZPLlwsTUuYJxwur3eG4tYabmzFRMeD9DQ/3FO4=
    - if: tag IS present
      env:
        - base=debian
        - image=ubuntu
        - tag=bionic
      deploy:
        provider: packagecloud
        skip_cleanup: true
        dist: ubuntu/bionic
        local_dir: dist/ubuntu/bionic/
        repository: softu2f
        username: danstiner
        token:
          secure: 0biLRJWDCLduK5qWfI5I1SwapD8HGaAQncsJf4lKyAwzZOLLjQAs7cIoIbcOEBXXUeqG4+3/+/eUWrjCYzMJJ0nh6ciiDFVkiibLzIQ3w25l2i9slCBW3hHDxtN18JDlI0lm19YhMU4pM3jc2Ulkmq0Ek/9625ob2MDl8apt2vUYyusWuoLck4A0iyyL7rgng510tNT3S+YzU05FwJ7cwtoqst1PIB6mhYfGsVytBx7HU2hSueZkMyR975sD4ZgSP/57yxuaSe5sASYd+xBR+w6I3zcBr2FObB2EbyE8r1aDCR25gpUMwrmnfBpw7grcn/UFKB7a+d5iB5qtY8YjJ25sWqriut20qZWilEK5OLh3vLg/H0vIkUU8+XBZC/0DC2zxITpSrTH7rhWOYkfD1o9dl3B3JmTtM4V4ah8H7t0dnLvMZQzfu6voUfkQVb9cVSDLaiu9BQqHER/7ngAC0treiPrH6gpcOVeUxkNknJqummxA5avcwqwvvvY6PXDWzoI+43Llk27fyM/o75yCUL6DuBjKhKBnIZv8XIEnov4hNFFwaKKNC6J3cvlh+I6SMCtxftUAgACDSgw1ZZAD0u9K9OMNMt+QvSpH2rN+QByCgO1oF8/lCP1mg/9ZWFnS6C+YfZPLlwsTUuYJxwur3eG4tYabmzFRMeD9DQ/3FO4=
    - if: tag IS present
      env:
        - base=debian
        - image=ubuntu
        - tag=xenial
      deploy:
        provider: packagecloud
        skip_cleanup: true
        dist: ubuntu/xenial
        local_dir: dist/ubuntu/xenial/
        repository: softu2f
        username: danstiner
        token:
          secure: 0biLRJWDCLduK5qWfI5I1SwapD8HGaAQncsJf4lKyAwzZOLLjQAs7cIoIbcOEBXXUeqG4+3/+/eUWrjCYzMJJ0nh6ciiDFVkiibLzIQ3w25l2i9slCBW3hHDxtN18JDlI0lm19YhMU4pM3jc2Ulkmq0Ek/9625ob2MDl8apt2vUYyusWuoLck4A0iyyL7rgng510tNT3S+YzU05FwJ7cwtoqst1PIB6mhYfGsVytBx7HU2hSueZkMyR975sD4ZgSP/57yxuaSe5sASYd+xBR+w6I3zcBr2FObB2EbyE8r1aDCR25gpUMwrmnfBpw7grcn/UFKB7a+d5iB5qtY8YjJ25sWqriut20qZWilEK5OLh3vLg/H0vIkUU8+XBZC/0DC2zxITpSrTH7rhWOYkfD1o9dl3B3JmTtM4V4ah8H7t0dnLvMZQzfu6voUfkQVb9cVSDLaiu9BQqHER/7ngAC0treiPrH6gpcOVeUxkNknJqummxA5avcwqwvvvY6PXDWzoI+43Llk27fyM/o75yCUL6DuBjKhKBnIZv8XIEnov4hNFFwaKKNC6J3cvlh+I6SMCtxftUAgACDSgw1ZZAD0u9K9OMNMt+QvSpH2rN+QByCgO1oF8/lCP1mg/9ZWFnS6C+YfZPLlwsTUuYJxwur3eG4tYabmzFRMeD9DQ/3FO4=

script: ./package.sh $base $image $tag
