#!/bin/sh

case "$1" in
    purge|remove)
        # Package removal, not upgrade
        systemctl --no-reload --user disable softu2f.service >/dev/null 2>&1 || true
    ;;

    *)
        # Other operation, no action needed
    ;;

esac

exit 0
