#!/bin/sh
set -e

# tmpfiles
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	# In case this system is running systemd, we need to ensure that all
	# necessary tmpfiles (if any) are created before starting.
	if [ -d /run/systemd/system ] ; then
		systemd-tmpfiles --create /usr/lib/tmpfiles.d/softu2f.conf >/dev/null || true
	fi
fi

# This will only remove masks created by deb-systemd-helper on package removal.
deb-systemd-helper unmask softu2f.socket >/dev/null || true

if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	if [ -n "$2" ]; then
		# Stop service on upgrade, rely on clients to start it up via the socket
		deb-systemd-invoke stop softu2f.socket >/dev/null || true
		deb-systemd-invoke stop softu2f.service >/dev/null || true
		deb-systemd-invoke start softu2f.socket >/dev/null || true
	else
		# Start socket listener on initial install
		deb-systemd-invoke preset softu2f.socket >/dev/null || true
		deb-systemd-invoke start softu2f.socket >/dev/null || true
	fi
fi

exit 0

