[workspace]
members = ["u2f-core", "u2fhid-protocol", "linux-uhid-sys", "linux-uhid-tokio", "linux-uhid-tokio/example", "user-daemon", "system-daemon"]

[profile.release]
lto = true
panic = 'abort'
backtrace = false

[patch.crates-io]
systemd = { git = "https://github.com/jmesmon/rust-systemd", branch = "master" }
